#!/bin/sh
echo Adding gpnbp User
adduser gpnbp --disabled-password --gecos "" --no-create-home

echo Adding files and permissons
touch /var/log/gpn-badge-printer.log
chown root:adm /var/log/gpn-badge-printer.log
chown root:gpnbp -R /opt/gpn-badge-printer/

echo Starting service...
systemctl daemon-reload
systemctl restart rsyslog
systemctl enable --now gpn-badge-printer.service
