name: Create Debian Package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build package
        run: dpkg -b src/ gpnbp.deb

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: docs-build
          path: gpnbp.deb