name: Create Debian Package
on:
  push:
    paths:
      - 'src/**'
      - 'web/**'
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
      - 'web/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
            node-version: 16

      - name: Install frontend dependencies
        run: npm install
        working-directory: web

      - name: Build frontend
        run: npm run build:prod
        working-directory: web

      - name: Create debian package
        run: |
            cp -r web/dist/ticket-scanner/* src/opt/gpn-badge-printer/frontend/
            cp conf.json src/opt/gpn-badge-printer/files/conf.json
            dpkg -b src/ gpnbp.deb

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: debian-build
          path: gpnbp.deb